name: Build Tampermonkey Script

on:
  push:
    branches: [main]
    paths:
      - 'src/MWI_Toolkit.ts'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install TypeScript
        run: npm install -g typescript

      - name: Compile TypeScript to JavaScript
        run: tsc src/MWI_Toolkit.ts --target ES2020 --outFile temp_output.js --removeComments false

      - name: Rebuild with Tampermonkey header and IIFE wrapper
        run: |
          # 提取 Tampermonkey header (前12行,不包括 IIFE 开始)
          head -n 12 src/MWI_Toolkit.ts > MWI_Toolkit.user.js
          echo "" >> MWI_Toolkit.user.js
          # 添加 IIFE 开始
          echo "(function () {" >> MWI_Toolkit.user.js
          # 添加编译后的代码主体(跳过开头的 'use strict')
          tail -n +2 temp_output.js >> MWI_Toolkit.user.js
          # 添加 IIFE 结束
          echo "})();" >> MWI_Toolkit.user.js

      - name: Upload compiled user script as artifact
        uses: actions/upload-artifact@v4
        with:
          name: MWI_Toolkit.user.js
          path: MWI_Toolkit.user.js